name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build OVA
        run:  |
          cd $GITHUB_WORKSPACE
          sudo chmod +x ./packages.sh && sudo ./packages.sh
          sudo chmod +x ./build.sh && sudo ./build.sh
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: "images/*.ova" 
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
