name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build OVA
        run:  |
          sudo chmod +x ./$GITHUB_WORKSPACE/packages.sh && sudo ./packages.sh   
          sudo chmod +x ./$GITHUB_WORKSPACE/build.sh && sudo ./build.sh
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: "images/*.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
